# Generated by Django 3.0.2 on 2020-01-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_home'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Landpage',
        ),
    ]
