# Generated by Django 3.0.2 on 2020-02-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='user',
        ),
    ]
