# Generated by Django 3.0.2 on 2020-02-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
