# Generated by Django 3.0.2 on 2020-02-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_ministries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
