# Generated by Django 3.0.2 on 2020-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_delete_home'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics')),
                ('position', models.TextField()),
                ('name_1', models.CharField(max_length=200)),
                ('img_1', models.ImageField(upload_to='pics')),
                ('position_1', models.TextField()),
                ('name_2', models.CharField(max_length=205)),
                ('img_2', models.ImageField(upload_to='pics')),
                ('position_2', models.TextField()),
            ],
        ),
    ]
