# Generated by Django 3.0.2 on 2020-02-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
