# Generated by Django 3.0.2 on 2020-02-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_1',
        ),
    ]
