# Generated by Django 3.0.2 on 2020-02-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_delete_home_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.CharField(max_length=255)),
                ('heading_2', models.CharField(max_length=255)),
                ('heading_3', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
