# Generated by Django 3.0.2 on 2020-02-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_home_1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
