# Generated by Django 3.0.2 on 2020-02-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_events'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home_1',
        ),
    ]
